src/Entity/Order.php
<?php

namespace App\Entity;

use App\Util\UtilString;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Persistence\Event\LifecycleEventArgs;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\OrderRepository")
 * @ORM\EntityListeners({"App\Listeners\OrderListener"})
 * @ORM\HasLifecycleCallbacks()
 * @ORM\Table(name="orders")
 */
class Order
{

    const CREATED_STATUS = 'CREATED';

    const PAYED_STATUS = 'PAYED';

    const REJECTED_STATUS = 'REJECTED';

    use TimestampableEntity;

    /**
     * @var int
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="IDENTITY")
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(type="string", length=255, unique=true, nullable=true)
     */
    private $code;

    /**
     * @var Customer
     * @ORM\ManyToOne(targetEntity="App\Entity\Customer", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $customer;

    /**
     * @var float
     * @ORM\Column(type="float")
     */
    private $totalToPay;

    /**
     * @var string
     * @ORM\Column(type="string", length=20)
     */
    private $status;

    /**
     * @var OrderDetail
     * @ORM\OneToMany(
     *     targetEntity="OrderDetail",
     *     mappedBy="orderReference",
     *     cascade={"persist"},
     *     orphanRemoval=true,
     *     fetch="EXTRA_LAZY"
     * )
     */
    private $details;

    /**
     * Constructor.
     */
    public function __construct()
    {
        $this->setStatus(self::CREATED_STATUS);
        $this->details = new ArrayCollection();
    }

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return null|string
     */
    public function getCode(): ?string
    {
        return $this->code;
    }

    /**
     * @param string $code
     * @return Order
     */
    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }

    /**
     * @return Customer|null
     */
    public function getCustomer(): ?Customer
    {
        return $this->customer;
    }

    /**
     * @param Customer|null $customer
     * @return Order
     */
    public function setCustomer(?Customer $customer): self
    {
        $this->customer = $customer;

        return $this;
    }

    /**
     * @return float|null
     */
    public function getTotalToPay(): ?float
    {
        return $this->totalToPay;
    }

    /**
     * @param float $totalToPay
     * @return Order
     */
    public function setTotalToPay(float $totalToPay): self
    {
        $this->totalToPay = $totalToPay;

        return $this;
    }

    /**
     * Returns the total to pay in money format
     * @return string
     */
    public function getFormattedTotalToPay(): string
    {
        return UtilString::getMoneyFormatOrEmpty($this->totalToPay);
    }

    /**
     * @return null|string
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * @param string $status
     * @return Order
     */
    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return Collection|null
     */
    public function getDetails(): ?Collection
    {
        return $this->details;
    }

    /**
     * @param OrderDetail $detail
     * @return Order
     */
    public function addDetail(OrderDetail $detail): self
    {
        if (!$this->details->contains($detail)) {
            $detail->setOrderReference($this);
            $this->details[] = $detail;
        }

        return $this;
    }

    /**
     * @param OrderDetail $detail
     * @return Order
     */
    public function removeDetail(OrderDetail $detail): self
    {
        if ($this->details->contains($detail)) {
            $this->details->removeElement($detail);
        }

        return $this;
    }
}

src/Entity/Product.php
<?php

namespace App\Entity;


use App\Util\UtilString;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 * @ORM\Table(name="products")
 */
class Product
{

    use TimestampableEntity;

    /**
     * @var int
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="IDENTITY")
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $name;

    /**
     * @var string
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @var float
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @var Category
     * @ORM\ManyToOne(targetEntity="App\Entity\Category")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @var string
     * @ORM\Column(type="string", length=255)
     */
    private $photo;

    /**
     * @return null|string
     */
    public function __toString()
    {
        return $this->getName();
    }

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return null|string
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @param string $name
     * @return Product
     */
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return null|string
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * @param string $description
     * @return Product
     */
    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return float|null
     */
    public function getPrice(): ?float
    {
        return $this->price;
    }

    /**
     * @param float $price
     * @return Product
     */
    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    /**
     * Returns the price in money format
     * @return null|string
     */
    public function getFormattedPrice(): string
    {
        return UtilString::getMoneyFormatOrEmpty($this->price);
    }

    /**
     * @return Category|null
     */
    public function getCategory(): ?Category
    {
        return $this->category;
    }

    /**
     * @param Category|null $category
     * @return Product
     */
    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return null|string
     */
    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    /**
     * @param string $photo
     * @return Product
     */
    public function setPhoto(string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }
}

src/Form/OrderType.php
<?php

namespace App\Form;

use App\Entity\Order;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Form to creates orders.
 * @package App\Form
 */
class OrderType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('customer', CustomerType::class)
            ->add('details', CollectionType::class, [
                'entry_type' => OrderDetailType::class,
                'allow_add' => true,
                'allow_delete' => false,
                'by_reference' => false,
                'entry_options' => [
                    'label' => false
                ]
            ])
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Order::class,
        ]);
    }
}

src/Controller/OrderController.php
<?php

namespace App\Controller;

use App\Entity\Order;
use App\Entity\PlacetoPayIntegration;
use App\Entity\Product;
use App\Form\OrderType;
use App\Managers\OrderManager;
use App\Services\PlacetoPay\PaymentRequest;
use App\Services\PlacetoPay\RequestInformation;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Exception\LogicException;

class OrderController extends AbstractController
{

    /**
     * @var OrderManager
     */
    private $orderManager;

    /**
     * Constructor.
     * @param OrderManager $orderManager
     */
    public function __construct(OrderManager $orderManager)
    {
        $this->orderManager = $orderManager;
    }

    /**
     * Action that shows the list of orders
     * @Route("/orders/list", name="list_order", methods={"GET"})
     * @return Response
     */
    public function index()
    {
        $orders = $this->getDoctrine()->getRepository(Order::class)->findAll();

        return $this->render('order/index.html.twig', [
            'orders' => $orders,
        ]);
    }

    /**
     * Action that creates a new pre order.
     * @param int $productId
     * @param Request $request
     * @Route("/order/new/product/{productId}", name="new_order", methods={"GET"})
     * @return Response
     */
    public function new(int $productId, Request $request)
    {
        $product = $this->getDoctrine()->getRepository(Product::class)->find($productId);
        $quantity = abs((int) $request->get('q', 1));

        if (!$product) {
            throw $this->createNotFoundException('El producto no existe!');
        }
        // create a new order
        $order = $this->orderManager->generatePreOrder($product, $quantity);
        // create order form
        $form = $this->createForm(OrderType::class, $order);

        return $this->render('order/new.html.twig', [
            'order' => $order,
            'detail' => $order->getDetails()->first(),
            'form' => $form->createView()
        ]);
    }

    /**
     * Action that creates an order.
     * @param Request $request
     * @Route("/order/create", name="create_order", methods={"POST"})
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
     */
    public function create(Request $request)
    {
        // create order form
        $form = $this->createForm(OrderType::class, new Order());
        $form->handleRequest($request);

        if ($form->isSubmitted() and $form->isValid()) {
            $order = $form->getData();
            $this->orderManager->createOrder($order);
            return $this->redirectToRoute('show_order', [
                'code' => $order->getCode()
            ]);
        }

        return $this->render('order/new.html.twig', [
            'order' => $form->getData(),
            'detail' => $form->getData()->getDetails()->first(),
            'form' => $form->createView()
        ]);

    }

    /**
     * Action that shows an order.
     * @param string $code
     * @Route("/order/{code}/show", name="show_order", methods={"GET"})
     * @return Response
     */
    public function show(string $code)
    {
        $order = $this->orderManager->getOrderByCode($code);

        if (!$order) {
            throw $this->createNotFoundException('La orden no existe!');
        }

        $isPayedStatus = $order->getStatus() == Order::PAYED_STATUS;

        return $this->render('order/show.html.twig', [
            'order' => $order,
            'is_payed_status' => $isPayedStatus,
            'detail' => $order->getDetails()->first()
        ]);
    }

    /**
     * @param PaymentRequest $paymentRequest
     * @param string $code
     * @Route("/order/{code}/pay", name="request_pay_order")
     * @return Response
     * @throws \Dnetix\Redirection\Exceptions\PlacetoPayException
     */
    public function pay(PaymentRequest $paymentRequest, string $code)
    {
        $order = $this->orderManager->getOrderByCode($code);

        if (!$order) {
            throw $this->createNotFoundException('La orden no existe!');
        }

        try {
            $redirect = $paymentRequest->sendPaymentRequest($order);
            return $this->redirect($redirect);
        } catch (LogicException $exception) {
            return $this->render('order/payment_request_error.html.twig', [
                'error' => $exception->getMessage()
            ]);
        }
    }

    /**
     * @param RequestInformation $requestInformation
     * @param string $code
     * @Route("/order/{code}/status", name="response_pay_order")
     * @return Response
     */
    public function status(RequestInformation $requestInformation, string $code)
    {
        $order = $this->orderManager->getOrderByCode($code);

        if (!$order) {
            throw $this->createNotFoundException('La orden no existe!');
        }

        try {
            // get integration record
            $ppIntegration = $this
                ->getDoctrine()
                ->getManager()
                ->getRepository(PlacetoPayIntegration::class)->getRecordByOrder($order)
            ;
            $requestInformation->process($ppIntegration->getRequestId(), $order);
            $orderApproved = $order->getStatus() == Order::PAYED_STATUS;
            return $this->render('order/status.html.twig', [
                'order' => $order,
                'approved' => $orderApproved
            ]);

        } catch (LogicException $exception) {
            return $this->render('order/payment_response_error.html.twig', [
                'order' => $order
            ]);
        }
    }
}

templates/order/index.html.twig
{% extends 'main.html.twig' %}

{% block title %}Listado de ordenes{% endblock %}

{% block content %}

   <div class="container-fluit">
    <h1 style="text-align:center">Listado Ordenes</h1>
      <div class="row justify-content-md-center">
        <div class="col">
          <img width="200" src="{{asset('img/list.jpg')}}" style="text-align:center"></img>
        </div>
         <div class="col-9 mt-3">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Orden N°</th>
                            <th scope="col">Refencia</th>
                            <th scope="col">CLiente</th>
                            <th scope="col">Estado</th>
                            <th scope="col">Total</th>
                            <th scope="col">fecha Orden</th>
                            <th scope="col">Ver</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for order in orders %}
                        <tr>
                            <th scope="row">{{ order.id }}</th>
                            <td>{{order.code}}</td>
                            <td>{{order.customer.name}}</td>
                            <td>{{order.status}}</td>
                            <td>{{order.totalToPay}}</td>
                            <td>{{order.createdAt.date|date("d/m/Y")}}</td>
                            <td>
                                <a class="btn btn-primary" href="{{ path('show_order', { code: order.code}) }}">
                                    Ver
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
         </div>
      </div>
   </div>
{% endblock %}

templates/order/new.html.twig
{% extends 'main.html.twig' %}

{% block title %}Comprar articulo{% endblock %}

{% block content %}

    <h1>Comprar Articulo</h1>


    <div class="row">
        <div class="col-7">
            <div class="card">
                <div class="card-header" style="color:cornflowerblue">
                    Datos del cliente
                </div>
                <div class="card-body">
                    {{ form_start(form,{
                        method: 'post',
                        action: path('create_order')
                    }) }}
                    {{ form_errors(form) }}
                    {{ form_widget(form) }}
                    <input type="submit" class="btn btn-info" value="Continuar">
                    {{ form_end(form) }}
                </div>
            </div>
        </div>

        <div class="col-5">
            <div class="card">
                <div class="card-body">
                    <h3>{{ detail.product.name }}</h3>
                    {{ include('product/_photo.html.twig', {
                        width: 200,
                        height: 200,
                        path: detail.product.photo
                    })}}
                    <h5>Cantidad: {{ detail.quantity }}</h5>
                    <h5>Precio Unitario: {{ detail.formattedPrice }}</h5>
                    <div>
                        <h4>Total a pagar: {{ order.formattedTotalToPay }}</h4>
                    </div>
                </div>

            </div>
        </div>
    </div>

{% endblock %}

templates/order/payment_request_error.html.twig
{% extends 'main.html.twig' %}

{% block title %}Error solictid de pago{% endblock %}

{% block content %}

    <h1>Error de solicitud de pago</h1>

    <div class="alert alert-danger">
        <p>
            {{ error }}
        </p>
    </div>


{% endblock %}

templates/order/payment_response_error.html.twig
{% extends 'main.html.twig' %}

{% block title %}Error de pago{% endblock %}

{% block content %}

    <h1>Error al realizar Pago</h1>

    <div class="alert alert-danger">
        <p>
            {{ error }}
        </p>
    </div>

    <div>
        <form method="post" action="{{ path('request_pay_order', { code: order.code }) }}">
            <button type="submit" class="btn btn-info btn-large">Reintentar</button>
        </form>
    </div>


{% endblock %}

templates/order/show.html.twig
{% extends 'main.html.twig' %}

{% block title %}Orden N°: {{ order.id }}{% endblock %}

{% block content %}

    <div class="container-fluit">
        <div class="row justify-content-md-center">
            <div class="col">
                <div class="card" style="width: 400px;">
                    <div class="card-header" style="color:cornflowerblue">
                        Orden N° {{ order.id }}
                    </div>
                    <div class="card-body" style="color:cornflowerblue">
                        <h5 class="card-title">Información Orden</h5>
                        <b class="card-text">Nombre:</b>
                        <span>{{ order.customer.name|capitalize }} </span>
                        </br>
                        <b class="card-text">Correo:</b>
                        <span>{{ order.customer.email }} </span>
                        </br>
                        <b class="card-text">Estado:</b>
                        <span>{{ order.status }} </span>
                        </br>
                        <b class="card-text">Total a pagar:</b>
                        <span>{{ order.totalToPay }} </span>

                        {%  if is_payed_status == false %}
                            <form class="mt-5" method="post" action="{{ path('request_pay_order', { code: order.code }) }}">
                                <button type="submit" class="btn btn-info btn-large">Pagar</button>
                            </form>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col col-lg-6">
                <img width="200" src="{{ asset('img/3582346.jpg') }}"></img>
            </div>
        </div>
        <div class="row justify-content-md-center mt-3">
            <div class="col-md-lg">
                <h3 style="text-align:center">Detalles Orden</h3>
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Codigo</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Descrición</th>
                        <th scope="col">Precio</th>
                        <th scope="col">Cantidad</th>
                        <th scope="col">Valor total</th>
                        <th scope="col"></th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <th scope="row">{{ detail.product.id }}</th>
                        <td>{{ detail.product.name }}</td>
                        <td>{{ detail.product.description }}</td>
                        <td>{{ detail.price }}</td>
                        <td>{{ detail.quantity }}</td>
                        <td>{{ detail.price * detail.quantity }}</td>
                        <td>
                            <img width="70" src="{{ asset(detail.product.photo) }}"> </img>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/order/status.html.twig
{% extends 'main.html.twig' %}

{% block title %}
    {% if approved == true %}
        Pago realizado!
    {% else %}
        Pago rechazado!
    {% endif %}
{% endblock %}

{% block content %}

    <h1>Estado de la orden</h1>

    {% if approved == true %}
        <div class="alert alert-success">
            <h4 class="badge badge-success">{{ order.status }}</h4>
            <p>
                El pago realizado para la orden No. {{ order.code }} fue aprobado.
            </p>
        </div>
        <div class="mt-5">
            <a class="btn btn-primary" href="{{ path('show_order', { code: order.code}) }}">
                Ver
            </a>
        </div>
    {% else %}
        <div class="alert alert-danger">
            <h4 class="badge badge-danger">{{ order.status }}</h4>
            <p>
                El pago realizado para la orden No. {{ order.code }} fue rechazado.
            </p>
        </div>
        <div>
            <form method="post" action="{{ path('request_pay_order', { code: order.code }) }}">
                <button type="submit" class="btn btn-info btn-large">Reintentar</button>
            </form>
        </div>
    {% endif %}

{% endblock %}